version: 2

sources:
  - name: dbt-project-430308
    schema: movies_project
    tables:
      - name: imdb_join_long_films
      - name: title
      - name: cpi_inflation_year_index
      - name: director_analysis_5films
      - name: finance_inflation
      - name: TMDB_movie_director